# Generated by Django 3.0.6 on 2020-09-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prediction_archive_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='prediction_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
            ],
        ),
    ]
